import random
from time import time,sleep
# List of Spanish Text 
spanish_chat =[
  "¿Qué te gusta hacer?",
  "Mi pasatiempo favorito es…",
  "¿Cuáles son tus pasatiempos?", 
  "¿Qué haces en tu tiempo libre?", 
  "Me gusta / No me gusta…",
  "Yo quiero, yo no quiero", 
  "¿Cuánto cuesta?", 
  "¿Qué hora es?",
  "¿Dónde está la estación de ferrocarril?",
  "¿Dónde hay un restaurante?",
  "Yo entiendo",
  "Yo no entiendo",
  "Una mesa para dos tres, cuatro",
  "Discúlpame",
  "Me gustaría disculparme contigo.",
  "Por favor, acepta mis más sinceras disculpas. ",
  "Olvídalo. ",
  "Esta bien, no hay problema. ",
  "ah, no te preocupes. ",
  "¿Te importaría ir más despacio? ",
  "¿Te importaría decirlo más lento? ",
  "¿Lo puedes decir más lento? ",
  "¿Puedes decirlo más lento? ",
  "¿Lo podrías decir más lento.",
  "¿Puedo Ayudarte? ",
  "¿Que tal una bebida? ",
  "Te gustaría que fuera? ",
  "Oh, si por favor. ",
  "Eso sería excelente, gracias.",
  "Por favor, me podrías dar una forma de contactarte.",
  "Puedes darme tu tarjeta?",
  "¿Hay alguna forma de contactarte?",
  "¿Cómo podemos estar en contacto? ",
  "Me encanta el chocolate. ",
  "Me fascina el chocolate.",
  "¿Dónde está el restaurante",
  "¿Dónde están los baños públicos?¿Cuándo sale el vuelo¿Cuánto cuesta un boleto de ida y vuelta?",
 " ¿Dónde está la parada de taxis?",
  "Quisiera una mesa, por favor., “¿Qué me recomienda?",
  "“Quisiera la cuenta, por favor.”",
 " ¿Puedo ver el menú?”",
  "No hablo español muy bien.”",
  "El Dinero",
  "¿Cuánto cuesta? ",
  " ¿Hablas inglés?",
   "¿Me podría ayudar?",
   "Permiso & Perdone",
   "El Desayuno - ",
   "La Ensalada",
   "La Carne - ",
]

# List of Japanese Text
japanese_chat = [
  "ありがとうございます",
  "お願いします ",
  " すみません ",
  "いいえ ",
  "ごめんなさい ",
  "わかりません" ,
  "日本語がわかりません ",
  "英語を話せますか？ ",
  "もう一度お願いします", 
  "はどこですか？",
  "交番 コンビニ ホテル トイレ",
  "いくらですか？",
  "ありますか?" ,
  "ごちそうさまでした" ,
  "どこでインターネットを使えますか",
  "いらっしゃいませ いらっしゃい ",
  "店内でお召し上がりですか？ ",
  "お持ち帰りですか? ",
  "喫煙ですか  禁煙ですか 大丈夫ですか？",
  "西日本から北日本の広い範囲で、",
  "大気の状態が非常に不安定になり、",
  "局地的に雷を伴って雨が強まっています。",
  "、落雷や竜巻などの突風のほか",
  "、急な激しい雨など、",
  "天気の急変に十分な注意が必要です。",
  "気象庁によりますと",
  "前線を伴った低気圧が",
  "日本付近を東へと進んでいて",
  "上空5500メートル付近には、",
  "この時期としては強い、マ",
  "イナス24度以下の寒気が流",
  "れ込んでいます。",
  "さらに、南からは暖かく湿",
  "った空気が流れ込んでいるた"
  "め、西日本から北日本の広い",
  "範囲で、大気の状態が非常に",
  "不安定になり、局地的に雷を",
  "伴って雨が強まっています。",
  "大気の不安定な状態は2日に",
  "かけて続く見通しで、局地的",
  "に積乱雲が発達し、雷や突風",
  "を伴って、激しい雨が降るお",
  "それがあります。",
  "気象庁は、落雷や竜巻などの",
  "突風、急な激しい雨のほか、",
  "「ひょう」にも十分注意す",
  "るよう呼びかけています。"
  "連休を利用して外出する",
  "かたもいると思います。",
  "天気の急変に注意し、",
  "▽急に冷たい風が強く吹く、",
  "▽周囲が暗くなるなど、",
]

# List of Chinese Text
chinese_chat = [
  "百工探秘图鉴",
  "那些鲜为人知的职业",
  "五一劳动节之际，",
  "新京报我们视频联合腾讯新闻推出",
  "《百工探秘图鉴》",
  "系列报道，",
  "用镜头揭秘十多个鲜为人知的或时下火热的行业，",
  "生动讲述从业者背后的故事。",
  "事里有年近七旬仍坚守在一线的“暗夜守护者”，",
  "有一年超200天与深山为伴的另类“铲屎官”",
  "有自带神秘面纱的“小鸡性别鉴定师”",
  "他们数年如一日坚守在自己的岗位上，",
  "兢兢业业，",
  "发光发热。　　",
  "病毒采集师：",
  "与新冠病毒近距离接触的9天",
  "新冠肺炎疫情期间，",
  "卢世栋参与了病毒毒株分离工作。",
  "卢世栋称，",
  "分离的难点在于疫情初期对病毒了解不够深入，",
  "以及高致病性传染病对实验环境、",
  "操作流程的极高要求。",
  "卢世栋印象最深刻的事",
  "是刚开始进入P3实验室，",
  "厚重的防护服，",
  "再加上N95口罩",
  "整个人呼吸会比较困难。",
  "”他回忆，有一天他们连续工作数小时，",
  "身体几乎到达极限，",
  "没有力气做任何动作或者说话",
  "在等待病毒灭活的30分钟里一动不动，",
  "吓坏了监控室的同事。",
  "同事赶忙通过对讲机询问状况，",
  "直到看到他们做了一个OK的手势",
  "才放下心来。",
  "经过9天的努力，",
  "卢世栋和同事成功分离出新冠病毒毒株，",
  "俩人击掌庆祝。",
  "完成了毒株分离，",
  "意味着拥有了疫苗的种子株，",
  "就可以用于制备疫苗，",
  "并且对研究新冠疫情规律等也具有积极的意义。",
  "卢世栋觉得疾控工作是一个非常神圣和伟大的事情，",
  "“只要能让大家远离病毒，",
  "哪怕我们每天跟病毒接触，",
  "这一切都是值得的”。",
  "暗夜守护者：年近70仍为还夜空一片星奔走",
  "在大气污染以及光污染之下，",
  "漫天繁星逐渐成为一种稀缺资源。",
  "为了保护夜空以及夜间活动的野生动物，",
]

def getOutput():
  n = random.randint(0,2)
  m = random.randint(0,49)
  language_chat = [spanish_chat,japanese_chat,chinese_chat]
  language = ["spanish","japanese","chinese"]
  output = language_chat[n][m]
  
  return print(output+" **"+language[n]+"-bot takeover**")

getOutput()
